const Projects = [
    {
        Id: '1',
        pImg:'/images/projects/img-1.jpg',
        slug:'Water-Line-Repair',
        subTitle:'Plumbing',
        title: 'Water Line Repair',
        description:'We are certified company. We provide best cleaning projects for you and your company Home projects and your Car.',
        spImg1:'/images/project-single/2.jpg',
        spImg2:'/images/project-single/3.jpg',
    },
    {
        Id: '2',
        pImg:'/images/projects/img-3.jpg',
        slug:'Basement-Plumbing',
        subTitle:'Plumbing',
        title: 'Basement Plumbing',
        description:'We are certified company. We provide best cleaning projects for you and your company Home projects and your Car.',
        spImg1:'/images/project-single/2.jpg',
        spImg2:'/images/project-single/3.jpg',
    },
    {
        Id: '3',
        pImg:'/images/projects/img-2.jpg',
        slug:'Remodeling-Service',
        subTitle:'Plumbing',
        title: 'Remodeling Service',
        description:'We are certified company. We provide best cleaning projects for you and your company Home projects and your Car.',
        spImg1:'/images/project-single/2.jpg',
        spImg2:'/images/project-single/3.jpg',
    },
    {
        Id: '4',
        pImg:'/images/projects/img-7.jpg',
        slug:'Water-Line-Repairs',
        subTitle:'Plumbing',
        title: 'Water Line Repair',
        description:'We are certified company. We provide best cleaning projects for you and your company Home projects and your Car.',
        spImg1:'/images/project-single/2.jpg',
        spImg2:'/images/project-single/3.jpg',
    },
    {
        Id: '5',
        pImg:'/images/projects/img-8.jpg',
        slug:'Kitchen-Plumbing',
        subTitle:'Plumbing',
        title: 'Kitchen Plumbing',
        description:'We are certified company. We provide best cleaning projects for you and your company Home projects and your Car.',
        spImg1:'/images/project-single/2.jpg',
        spImg2:'/images/project-single/3.jpg',
    },
    {
        Id: '6',
        pImg:'/images/projects/img-9.jpg',
        slug:'Gas-Line-Services',
        subTitle:'Plumbing',
        title: 'Gas Line Services',
        description:'We are certified company. We provide best cleaning projects for you and your company Home projects and your Car.',
        spImg1:'/images/project-single/2.jpg',
        spImg2:'/images/project-single/3.jpg',
    },
    {
        Id: '7',
        pImg:'/images/projects/img-6.jpg',
        slug:'Kitchen-Plumber',
        subTitle:'Plumbing',
        title: 'Kitchen Plumbing',
        description:'We are certified company. We provide best cleaning projects for you and your company Home projects and your Car.',
        spImg1:'/images/project-single/2.jpg',
        spImg2:'/images/project-single/3.jpg',
    },
    {
        Id: '8',
        pImg:'/images/projects/img-10.jpg',
        slug:'Basement-Plumber',
        subTitle:'Plumbing',
        title: 'Basement Plumbing',
        description:'We are certified company. We provide best cleaning projects for you and your company Home projects and your Car.',
        spImg1:'/images/project-single/2.jpg',
        spImg2:'/images/project-single/3.jpg',
    },
    {
        Id: '9',
        pImg:'/images/projects/img-11.jpg',
        slug:'Remodeling-Services',
        subTitle:'Plumbing',
        title: 'Remodeling Service',
        description:'We are certified company. We provide best cleaning projects for you and your company Home projects and your Car.',
        spImg1:'/images/project-single/2.jpg',
        spImg2:'/images/project-single/3.jpg',
    },
]
export default Projects;