const Services = [
    {
        Id: '1',
        sImg:'/images/service/1.jpg',
        sIcon:'/images/icon/kitchen-utensils.png',
        slug:'Kitchen-Plumbing',
        sTitle: 'Kitchen Plumbing',
        description:'Electronic typesetting rema essentially unchanged was popularised.',
        ssImg1:'/images/service-single/2.jpg',
        ssImg2:'/images/service-single/3.jpg',
    },
    {
        Id: '2',
        sImg:'/images/service/2.jpg',
        sIcon:'/images/icon/gas-stove.png',
        slug:'Gas-Line-Services',
        sTitle: 'Gas Line Services',
        description:'Electronic typesetting rema essentially unchanged was popularised.',
        ssImg1:'/images/service-single/2.jpg',
        ssImg2:'/images/service-single/3.jpg',
    },
    {
        Id: '3',
        sImg:'/images/service/3.jpg',
        sIcon:'/images/icon/water-tap.png',
        slug:'Water-Line-Repair',
        sTitle: 'Water Line Repair',
        description:'Electronic typesetting rema essentially unchanged was popularised.',
        ssImg1:'/images/service-single/2.jpg',
        ssImg2:'/images/service-single/3.jpg',
    },
    {
        Id: '4',
        sImg:'/images/service/4.jpg',
        sIcon:'/images/icon/sink.png',
        slug:'Bathroom-Plumbing',
        sTitle: 'Bathroom Plumbing',
        description:'Electronic typesetting rema essentially unchanged was popularised.',
        ssImg1:'/images/service-single/2.jpg',
        ssImg2:'/images/service-single/3.jpg',
    },
    {
        Id: '5',
        sImg:'/images/service/5.jpg',
        sIcon:'/images/icon/basement.png',
        slug:'Basement-Plumbing',
        sTitle: 'Basement Plumbing',
        description:'Electronic typesetting rema essentially unchanged was popularised.',
        ssImg1:'/images/service-single/2.jpg',
        ssImg2:'/images/service-single/3.jpg',
    },
    {
        Id: '6',
        sImg:'/images/service/6.jpg',
        sIcon:'/images/icon/remodeling.png',
        slug:'Remodeling-Service',
        sTitle: 'Remodeling Service',
        description:'Electronic typesetting rema essentially unchanged was popularised.',
        ssImg1:'/images/service-single/2.jpg',
        ssImg2:'/images/service-single/3.jpg',
    }
]
export default Services;